### ISSUE TITLE
Unable to Install the Package with Python Version 3.12.2

### ISSUE THREAD

**Issue by sarafrr** [theirstory/gliner-spacy#4]
Thanks for the integration in spaCy!

I've seen that using the last Python version `python=3.12.2` it is not possible to install the package and there is the following error:

```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-audnbid4\sentencepiece_54d49500fdd941e69df21f4a597fb6ec\setup.py", line 126, in <module>
          subprocess.check_call([
        File "C:\Users\user\AppData\Local\miniconda3\envs\test\Lib\subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\miniconda3\envs\test\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\miniconda3\envs\test\Lib\subprocess.py", line 1026, in _init_
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\user\AppData\Local\miniconda3\envs\test\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]
```
I've also created a new plain virtual environment (with conda) to test it, obtaining the same error.
I've created a new virtual environment, utilising an older version of Python `3.9.19`, and it was possible to install the package.

Thanks for the support,
Sara

**Comment by sarafrr** [comment]
Ok, I've just read the `setup.py` where you specified the Python version that you tested.
```
classifiers=[
        'Development Status :: 3 - Alpha',  
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
    ],
    python_requires='>=3.7',
```
Maybe, put `python_requires'>=3.7,<=3.10`.

Moreover, I've seen that to make the package function it is necessary to reinstall `numpy` and then `scipy`.
Sara

**Comment by wjbmattingly** [comment]
Thanks for this! I'll make these edits and update accordingly after some testing on my end.

**Comment by wjbmattingly** [comment]
Thanks again. This has now been resolved: https://github.com/theirstory/gliner-spacy/commit/29779d34c837c3df12df255063b055b0898faaae
